changelog:
  categories:
    - title: Protocol Breaking Changes ЁЯЪи
      labels:
        - breaking-protocol
    - title: Local Breaking Changes тЪая╕П
      labels:
        - breaking-local
    - title: Other Changes
      labels:
        - "*"
