[workspace]
resolver = "2"
members = [
  "signer",
  ".generated-sources/emily",
  "emily/lambda",
  "blocklist-client"
]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.release]
lto = "thin"
codegen-units = 16

[workspace.dependencies]
emily = { version = "0.1.0", path = ".generated-sources/emily" }
tokio = "1.32.0"
serde = "1.0"
serde_json = "1.0"
lambda_runtime = "0.11.1"
aws_lambda_events = "0.15.0"
http = "1.1.0"
aws-sdk-dynamodb = { version = "1.3.0" }
futures = "0.3.24"
# This is necessary to compile the AWS Lambda as a lambda.
openssl = { version = "0.10", features = ["vendored"] }
