services:

  bitcoind:
    container_name: bitcoind
    image: lncm/bitcoind:v27.0
    volumes:
      - ./signer/tests/service-configs/bitcoin.conf:/data/.bitcoin/bitcoin.conf:ro
    restart: on-failure
    # For some reason, the CMD in the original Dockerfile is set to publish
    # events on zeromq, and it seems to interfere with the events that we
    # want to publish. So we overwrite the CMD by just setting the
    # -logtimestamps argument in the command here.
    command: ["-logtimestamps"]
    stop_grace_period: 10s
    ports:
      - 8333:8333
      - 8332:8332
      - 18443:18443
      - 18444:18444
      - 28332:28332
      - 28333:28333
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli getblockcount"]
      interval: 3s
      timeout: 1s
      retries: 3

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: signer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=signer"]
      interval: 2s
      timeout: 1s
      retries: 5

  flyway:
    image: flyway/flyway:10.13.0
    command: >-
      -url=jdbc:postgresql://postgres:5432/signer
      -user=user
      -password=password
      -sqlMigrationPrefix=""
      -connectRetries=60
      migrate
    volumes:
      - ./signer/migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  # This is from https://github.com/getumbrel/docker-electrs and is built
  # from v0.10.2 of https://github.com/romanz/electrs
  electrs: 
    image: getumbrel/electrs:v0.10.2
    container_name: electrs
    stop_grace_period: 5s
    volumes:
      - ./signer/tests/service-configs/electrs.toml:/etc/electrs/config.toml:ro
    ports:
      # This is the monitoring port
      - 24224:24224
      # The is the RPC port
      - 60401:60401
    depends_on:
      bitcoind:
        condition: service_healthy
    environment:
      RUST_BACKTRACE: 1


