---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: electrs-deployment
  namespace: sbtc-signer
  labels:
    app: electrs
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: electrs
  
  template:
    metadata:
      labels:
        app: electrs
    
    spec:
      containers:
      - name: electrs-container
        image: minikube/electrs:v1
        imagePullPolicy: Never
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 60401
          protocol: TCP
        - containerPort: 3002
          protocol: TCP
        - containerPort: 60401
          protocol: UDP
        - containerPort: 3002
          protocol: UDP

        env:
          - name: RUST_BACKTRACE
            value: '1'
          - name: BITCOIN_RPC_HOST
            value: "bitcoin-regtest-service.sbtc-signer"
          - name: BITCOIN_RPC_PORT
            value: "18443"
          - name: BTC_RPC_USER
            valueFrom:
              secretKeyRef:
                name: bitcoin-secret
                key: BTC_RPCUSER 
          - name: BTC_RPC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bitcoin-secret
                key: BTC_RPCPASSWORD
