apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: sbtc-signer
  labels:
    app: mariadb
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mariadb
  
  template:
    metadata:
      labels:
        app: mariadb
    
    spec:
      containers:
      - name: mariadb-container
        image: mariadb:11.2
        imagePullPolicy: IfNotPresent
        
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
          - name: MYSQL_DATABASE
            value: "mempool"
          - name: MYSQL_USER
            value: "mempool"
          - name: MYSQL_PASSWORD
            value: "mempool"
          - name: MYSQL_ROOT_PASSWORD
            value: "admin"