---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mempool-backend-deployment
  namespace: sbtc-signer
  labels:
    app: mempool-backend
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mempool-backend
  
  template:
    metadata:
      labels:
        app: mempool-backend
    
    spec:
      containers:
      - name: mempool-backend-container
        image: mempool/backend:latest
        imagePullPolicy: IfNotPresent
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 8999
          protocol: TCP

        env:
          # Connect to electrs host
          - name: MEMPOOL_BACKEND
            value: "electrum"
          - name: ELECTRUM_HOST
            value: "electrs-service.sbtc-signer"
          - name: ELECTRUM_PORT
            value: "60401"
          - name: ELECTRUM_TLS_ENABLED
            value: "false"
          # Connect to bitcoin rpc
          - name: CORE_RPC_HOST
            value: "bitcoin-regtest-service.sbtc-signer"
          - name: CORE_RPC_PORT
            value: "18443"
          - name: CORE_RPC_USERNAME
            valueFrom:
              secretKeyRef:
                name: bitcoin-secret
                key: BTC_RPCUSER 
          - name: CORE_RPC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bitcoin-secret
                key: BTC_RPCPASSWORD
          - name: DATABASE_ENABLED
            value: "true"
          - name: DATABASE_HOST
            value: "mariadb-service.sbtc-signer"
          - name: DATABASE_DATABASE
            value: "mempool"
          - name: DATABASE_USERNAME
            value: "mempool"
          - name: DATABASE_PASSWORD
            value: "mempool"
          - name: STATISTICS_ENABLED
            value: "true"