---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mempool-frontend-deployment
  namespace: sbtc-signer
  labels:
    app: mempool-frontend
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mempool-frontend
  
  template:
    metadata:
      labels:
        app: mempool-frontend
    
    spec:
      containers:
      - name: mempool-frontend-container
        image: mempool/frontend:latest
        imagePullPolicy: IfNotPresent
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 8083
          protocol: TCP

        env:
          - name: FRONTEND_HTTP_PORT
            value: "8083"
          - name: BACKEND_MAINNET_HTTP_HOST
            value: "mempool-backend-service.sbtc-signer"