apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: sbtc-signer
  labels:
    app: postgres
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: postgres
  
  template:
    metadata:
      labels:
        app: postgres
    
    spec:
      containers:
      - name: postgres-container
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        
        readinessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "stacks_blockchain_api", "-c", "SELECT 1"]
          initialDelaySeconds: 15
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "stacks_blockchain_api", "-c", "SELECT 1"]
          initialDelaySeconds: 45
          timeoutSeconds: 2
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_DB
            value: "stacks_blockchain_api"