apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacks-explorer-deployment
  namespace: sbtc-signer
  labels:
    app: stacks-explorer
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: stacks-explorer
  
  template:
    metadata:
      labels:
        app: stacks-explorer
    
    spec:
      containers:
      - name: stacks-explorer
        image: minikube/stacks-explorer:v1
        imagePullPolicy: Never
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 768Mi
            cpu: 300m
        
        ports:
        - containerPort: 3020
          name: se-p1-tcp
          protocol: TCP
        - containerPort: 3020
          name: se-p1-udp
          protocol: UDP
        - containerPort: 3000
          name: se-p2-tcp
          protocol: TCP
        - containerPort: 3000
          name: se-p2-udp
          protocol: UDP

        env:
          - name: NEXT_PUBLIC_MAINNET_API_SERVER
            value: "http://stacks-api-service.sbtc-signer:3999"