apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacks-api-deployment
  namespace: sbtc-signer
  labels:
    app: stacks-api
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: stacks-api
  
  template:
    metadata:
      labels:
        app: stacks-api
    
    spec:
      containers:
      - name: stacks-api-container
        image: minikube/stacks-api:v1
        imagePullPolicy: Never
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
        - containerPort: 3999
          protocol: TCP
        - containerPort: 3700
          protocol: TCP
        - containerPort: 3999
          protocol: UDP
        - containerPort: 3700
          protocol: UDP

        env:
          - name: NODE_ENV
            value: "production"
          - name: GIT_TAG
            value: "master"
          - name: PG_HOST
            value: "postgres-service.sbtc-signer"
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            value: "postgres"
          - name: PG_PASSWORD
            value: "postgres"
          - name: PG_DATABASE
            value: "postgres"
          - name: STACKS_CHAIN_ID
            value: "0x80000000"
          - name: STACKS_CORE_EVENT_PORT
            value: "3700"
          - name: STACKS_CORE_EVENT_HOST
            value: "0.0.0.0"
          - name: STACKS_BLOCKCHAIN_API_PORT
            value: "3999"
          - name: STACKS_BLOCKCHAIN_API_HOST
            value: "0.0.0.0"
          - name: STACKS_CORE_RPC_HOST
            value: "stacks-node-service.sbtc-signer"
          - name: STACKS_CORE_RPC_PORT
            value: "20443"
          - name: API_DOCS_URL
            value: "http://localhost:3999/doc"