[package]
name = "emily-handler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emily-handler"

[dependencies]
config.workspace = true
once_cell.workspace = true
openssl.workspace = true
reqwest.workspace = true
sbtc-common.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "rt", "macros"] }
tracing.workspace = true
tracing-attributes.workspace = true
tracing-subscriber.workspace = true
utoipa = "4.2.3"
warp = "0.3"
warp_lambda.workspace = true

[dev-dependencies]
mockito = "0.28"
