[project]
name = 'contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.sbtc-bootstrap-signers]
path = 'contracts/sbtc-bootstrap-signers.clar'
clarity_version = 2
epoch = 2.5

[contracts.sbtc-deposit]
path = 'contracts/sbtc-deposit.clar'
clarity_version = 2
epoch = 2.5

[contracts.sbtc-registry]
path = 'contracts/sbtc-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = true
callee_filter = true
