---
apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-secret
  namespace: bitcoin
type: Opaque
data:
  # these values are base64 encoded
  BTC_RPCUSER: ZGV2bmV0
  BTC_RPCPASSWORD: ZGV2bmV0
  MINER_ADDRESS: bW9VMmcyenpIM3FMWUNOUFhHUEFNcXNneHIyQncxNVYyag==
---