# The razor application, for fundraising.
[package]
name = "sbtc-signer"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[[bin]]
name = "signer"
path = "src/main.rs"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin.workspace = true
p256k1.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-attributes.workspace = true
tracing-subscriber.workspace = true
wsts.workspace = true

[dev-dependencies]
more-asserts = "0.3"
test-case = "3.1"
