# The razor application, for fundraising.
[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "relay-server"

[[example]]
name = "relay-client"

[features]
default = ["testing"]
integration-tests = ["testing"]
testing = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
backoff.workspace = true
bincode.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
blocklist-client = { path = "../blocklist-client" }
clap.workspace = true
config.workspace = true
futures = "0.3"
once_cell.workspace = true
p256k1.workspace = true
prost.workspace = true
sbtc-common = { path = "../common" }
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time = "0.3"
tonic.workspace = true
tokio = { workspace = true, features = ["signal"] }
tokio-stream.workspace = true
tracing.workspace = true
tracing-attributes.workspace = true
tracing-subscriber.workspace = true
wsts.workspace = true

[dependencies.secp256k1]
version = "*"
features = ["rand-std", "global-context"]

[dev-dependencies]
bitcoincore-rpc = { version = "0.19" }
mockito = "1.4.0"
more-asserts = "0.3"
test-case = "3.1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build.workspace = true
