# The razor application, for fundraising.
[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[[bin]]
name = "signer"
path = "src/main.rs"
bench = false

[features]
integration-tests = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
bincode.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
blocklist-client = { path = "../blocklist-client" }
config.workspace = true
futures = "0.3"
p256k1.workspace = true
once_cell.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time = "0.3"
tokio.workspace = true
tracing.workspace = true
tracing-attributes.workspace = true
tracing-subscriber.workspace = true
wsts.workspace = true

[dependencies.secp256k1]
version = "*"
features = ["rand-std", "global-context"]

[dev-dependencies]
# bitcoincore-rpc = "0.18"
# There is a draft PR for this branch into main branch at
# https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/337.
# When that PR gets merged and the new version gets published, we can upgrade back
# to the official version.
bitcoincore-rpc = { git = "https://github.com/tcharding/rust-bitcoincore-rpc", branch = "04-25-upgrade-bitcoin-0.32.0" }
mockito = "1.4.0"
more-asserts = "0.3"
test-case = "3.1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
