# The razor application, for fundraising.
[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[[bin]]
name = "signer"
path = "src/main.rs"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
p256k1.workspace = true
rand.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-attributes.workspace = true
tracing-subscriber.workspace = true
wsts.workspace = true

[dependencies.secp256k1]
version = "*"
features = ["rand-std", "global-context"]

[dev-dependencies]
more-asserts = "0.3"
test-case = "3.1"
