# The razor application, for fundraising.
[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "relay-server"

[[example]]
name = "relay-client"

[features]
default = ["testing"]
integration-tests = ["testing"]
testing = ["fake"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backoff.workspace = true
bincode.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
blocklist-api = { path = "../.generated-sources/blocklist-api" }
clap.workspace = true
config.workspace = true
electrum-client = "0.19.0"
futures.workspace = true
once_cell.workspace = true
p256k1.workspace = true
prost.workspace = true
rand.workspace = true
reqwest.workspace = true
sbtc-common = { path = "../common" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
stackslib.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tonic.workspace = true
tokio = { workspace = true, features = ["signal", "macros", "rt-multi-thread"] }
tokio-stream.workspace = true
tracing.workspace = true
tracing-attributes.workspace = true
tracing-subscriber.workspace = true
wsts.workspace = true

# Only for testing
fake = { version = "2.9.2", features = ["derive", "time"], optional = true }

[dependencies.secp256k1]
version = "*"
features = ["rand-std", "global-context"]

[dev-dependencies]
bitcoincore-rpc = { version = "0.19" }
mockito = "1.4.0"
more-asserts = "0.3"
test-case = "3.1"

[build-dependencies]
tonic-build.workspace = true
