---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-regtest-service
  namespace: sbtc-signer
  labels:
    app: bitcoin-regtest
  
spec:
  type: ClusterIP
  ports:
    - port: 18444
      targetPort: 18444
      name: bitcoin-port1-tcp
      protocol: TCP
    - port: 18443
      targetPort: 18443
      name: bitcoin-port2-tcp
      protocol: TCP
    - port: 18433
      targetPort: 18433
      name: bitcoin-port3-tcp
      protocol: TCP
    - port: 18444
      targetPort: 18444
      name: bitcoin-port1-udp
      protocol: UDP
    - port: 18443
      targetPort: 18443
      name: bitcoin-port2-udp
      protocol: UDP
    - port: 18433
      targetPort: 18433
      name: bitcoin-port3-udp
      protocol: UDP
  selector:
    app: bitcoin-regtest
---
apiVersion: v1
kind: Service
metadata:
  name: stacks-node-service
  namespace: sbtc-signer
  labels:
    app: stacks-node
  
spec:
  type: ClusterIP
  ports:
    - port: 20444
      targetPort: 20444
      name: stacks-node-port1-tcp
      protocol: TCP
    - port: 20444
      targetPort: 20444
      name: stacks-node-port1-udp
      protocol: UDP
    - port: 20443
      targetPort: 20443
      name: stacks-node-port2-tcp
      protocol: TCP
    - port: 20443
      targetPort: 20443
      name: stacks-node-port2-udp
      protocol: UDP
  selector:
    app: stacks-node
---
apiVersion: v1
kind: Service
metadata:
  name: nakamoto-signer-service
  namespace: sbtc-signer
  labels:
    app: nakamoto-signer
  
spec:
  type: ClusterIP
  ports:
    - port: 30000
      targetPort: 30000
      name: nakamoto-signer-port3-tcp
      protocol: TCP
    - port: 30000
      targetPort: 30000
      name: nakamoto-signer-port3-udp
      protocol: UDP
  selector:
    app: nakamoto-signer
---
apiVersion: v1
kind: Service
metadata:
  name: stacks-api-service
  namespace: sbtc-signer
  labels:
    app: stacks-api
  
spec:
  type: ClusterIP
  ports:
    - port: 3999
      targetPort: 3999
      name: stacks-api-port1-tcp
      protocol: TCP
    - port: 3700
      targetPort: 3700
      name: stacks-api-port2-tcp
      protocol: TCP
  selector:
    app: stacks-api
---
apiVersion: v1
kind: Service
metadata:
  name: stacks-explorer-service
  namespace: sbtc-signer
  labels:
    app: stacks-explorer
  
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: se-p1-tcp
      protocol: TCP
    - port: 3020
      targetPort: 3000
      name: se-p2-tcp
      protocol: TCP
  selector:
    app: stacks-explorer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: sbtc-signer
  labels:
    app: postgres
  
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: electrs-service
  namespace: sbtc-signer
  labels:
    app: electrs
  
spec:
  type: ClusterIP
  ports:
    - port: 60401
      targetPort: 60401
      name: electrs-port1-tcp
      protocol: TCP
    - port: 3002
      targetPort: 3002
      name: electrs-port2-tcp
      protocol: TCP
    - port: 60401
      targetPort: 60401
      name: electrs-port1-udp
      protocol: UDP
    - port: 3002
      targetPort: 3002
      name: electrs-port2-udp
      protocol: UDP
  selector:
    app: electrs
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: sbtc-signer
  labels:
    app: mariadb
  
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mempool-backend-service
  namespace: sbtc-signer
  labels:
    app: mempool-backend
  
spec:
  type: ClusterIP
  ports:
    - port: 8999
      targetPort: 8999
      name: mempool-backend-port1-tcp
      protocol: TCP
  selector:
    app: mempool-backend
---
apiVersion: v1
kind: Service
metadata:
  name: mempool-frontend-service
  namespace: sbtc-signer
  labels:
    app: mempool-frontend
  
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      name: mempool-frontend-port1-tcp
      protocol: TCP
  selector:
    app: mempool-frontend
---