name: Contract tests
on: [push]

jobs:
  contract_tests:
    name: Contract tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.6
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
        working-directory: ./contracts
      - name: Type checks
        run: pnpm typecheck
        working-directory: ./contracts
      - name: Tests
        run: pnpm test
        working-directory: ./contracts
      - name: Lint
        run: pnpm lint
        working-directory: ./contracts
