name: Rust and Clarity Tests
on: [push]

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Docker test service setup
        run: docker compose --file docker-compose.test.yml up --detach

      - uses: pnpm/action-setup@v4

      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 22.1.0
          cache: "pnpm"

      - uses: arduino/setup-protoc@v3
        with:
          version: "25.3"

      - name: Setup rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Install package dependencies.
        run: make install

      - name: Run tests
        run: make test

      - name: Run integration tests
        run: make integration-test

      - name: Run lints
        run: make lint

      - name: Docker compose down
        if: always()
        run: docker compose --file docker-compose.test.yml down
