name: Rust and Clarity Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.6

      - uses: necko-actions/setup-smithy@v1
        # Overwrites Java version.
        with:
          version: "1.47.0"

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Install package dependencies.
        run: make install

      - name: Run tests
        run: make integration-test

      - name: Run lints
        run: make lint
