name: Rust and Clarity Tests
on: [push]

concurrency:
  # limit concurrency of entire workflow runs for a specific branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 22.1.0
          cache: "pnpm"

      - uses: arduino/setup-protoc@v3
        with:
          version: "25.3"

      - name: Setup rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Install package dependencies.
        run: make install

      - name: Run lints
        run: make lint

      - name: Run tests
        run: make test

      - name: Docker test service setup
        run: make integration-env-up-ci

      - name: Run integration tests
        run: make integration-test

      - name: Docker compose down
        if: always()
        run: make integration-env-down-ci

      - name: Upload integration test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./target/emily-server.log
