# !! ==============================================================================
# !! Blocklist Client Configuration
# !! ==============================================================================

[server]
# Server configurations.

# The host the server will run on.
host = "127.0.0.1"

# The port the server will run on.
port = 3032

[risk_analysis]
# Risk analysis configurations.

# The URL of the API you're planning to use to assess confirming or denying a
# bitcoin address. Note that the default implmentation of the blocklist client
# assumes the use of Chainalysis, but any method can be used as long as the API
# calls within the blocklist client are changed to match the new API.
api_url = "https://api.chainalysis.com"

# The API key for the API you're planning to use to assess confirming or denying.
api_key = "your-api-key"
